version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wildfire_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - climate-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d wildfire_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:6-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    networks:
      - climate-net

  kestra:
    image: kestra/kestra:latest
    command: server local
    environment:
      KESTRA_CONFIGURATION: |
        kestra:
          tasks:
            scripts:
              docker:
                volume-enabled: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - shared-data:/shared-data
    ports:
      - "8080:8080"
    networks:
      - climate-net

  api:
    build: ./backend
    volumes:
      - ./backend:/app
      - shared-data:/shared-data
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - climate-net
    environment:
      DATABASE_URL: postgresql://user:password@postgres/wildfire_db
      MONGO_URL: mongodb://user:password@mongo:27017

volumes:
  postgres_data:
  mongo_data:
  shared-data:


networks:
  climate-net:
