version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - climate-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:6-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - climate-net

  kestra:
    image: kestra/kestra:latest
    entrypoint: [ "/init-permissions.sh" ]
    command: [ "server", "local" ]
    environment:
      KESTRA_CONFIGURATION: |
        kestra:
          server:
            basic-auth:
              enabled: false
          tasks:
            scripts:
              docker:
                volume-enabled: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - shared-data:/shared-data
      - ./kestra/scripts/init-permissions.sh:/init-permissions.sh:ro
    ports:
      - "8080:8080"
    networks:
      - climate-net

  api:
    build: ./backend
    volumes:
      - ./backend:/app
      - shared-data:/shared-data
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - climate-net
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      MONGO_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017

volumes:
  postgres_data:
  mongo_data:
  shared-data:


networks:
  climate-net:
